version: "3.7"
services:
  app:
    image: hive_sbi_webapp:0.1.0
    expose:
      - "8000"
    command: ["sh", "/app/boot_scripts/app.sh"]
    build:
      args:
        - DJANGO_ENV=prod

  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
